# Dataset
[truongpdd/vietnamese_poetry](https://huggingface.co/datasets/truongpdd/vietnamese_poetry)

In [1]:
from datasets import load_dataset

dataset = load_dataset('truongpdd/vietnamese_poetry')

Downloading:   0%|          | 0.00/717 [00:00<?, ?B/s]

Extracting data files:   0%|          | 0/1 [00:00<?, ?it/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/parquet/truongpdd--vietnamese_poetry-a78eb18695f6197f/0.0.0/0b6d5799bb726b24ad7fc7be720c170d8e497f575d02d47537de9a5bac074901. Subsequent calls will reuse this data.


  0%|          | 0/1 [00:00<?, ?it/s]

In [2]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'the_loai'],
        num_rows: 171188
    })
})

In [3]:
print(dataset['train'][0]['text'])
# print('\n'.join(dataset['train'][:2]['text']))

thơ lục bát: 
 ai ơi xa bến quê hương
nhớ về quê mẹ nắng sương đây nè
nhớ sao những buổi trưa hè
võng đưa cót két gió hè hiu hiu
lời ru của mẹ dấu yêu
ngọt ngào êm dịu mẹ yêu con nhiều
lời mẹ năm tháng sớm chiều
con nghe nhớ mãi những điều ru ta
lòng mẹ ôi thật bao la
thái bình rộng lớn thương là mênh mông
một đời lưng mẹ đã còng
vai mang tay xách lo chồng chăm con
mong sao con lớn nên người
thân mẹ có cực vẫn cười thương con
vì đời mẹ sống cho con
gom bao mệt nhọc mãi còn vòng tay
mong chờ cho đến một ngày
công thành danh toại là ngày mẹ mong
dù nay mẹ đã xa rồi
con đây nhớ mãi mẹ ôi vạn lần
nguyện rằng ghi nhớ công ân
sinh thành dưỡng dục mẫu thân đời đời


In [4]:
text = '\n'.join(dataset['train'][:]['text'])
len(text)

83454368

In [5]:
print(text[:100])

thơ lục bát: 
 ai ơi xa bến quê hương
nhớ về quê mẹ nắng sương đây nè
nhớ sao những buổi trưa hè
võn


In [6]:
chars = sorted(list(set(text)))
vocab_size = len(chars)
print('chars:',chars)
print('vocab_size:', vocab_size)

chars: ['\x08', '\n', ' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', '=', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '|', '~', '¡', '¢', '¤', '¥', '¬', '\xad', '°', '²', '³', '´', 'µ', '¸', '¹', 'à', 'á', 'â', 'ã', 'ä', 'å', 'ç', 'è', 'é', 'ê', 'ë', 'ì', 'í', 'î', 'ï', 'ñ', 'ò', 'ó', 'ô', 'õ', 'ö', 'ø', 'ù', 'ú', 'û', 'ü', 'ý', 'ÿ', 'ā', 'ă', 'ą', 'ć', 'đ', 'ē', 'ę', 'ě', 'ĩ', 'ī', 'ń', 'ō', 'œ', 'š', 'ť', 'ũ', 'ū', 'ů', 'ơ', 'ƣ', 'ư', 'ǎ', 'ǒ', 'ǚ', 'ǵ', 'ǹ', '̀', '́', '̂', '̃', '̉', '̣', 'γ', 'с', 'ц', 'ḥ', 'ḷ', 'ḿ', 'ṃ', 'ṇ', 'ṕ', 'ṭ', 'ạ', 'ả', 'ấ', 'ầ', 'ẩ', 'ẫ', 'ậ', 'ắ', 'ằ', 'ẳ', 'ẵ', 'ặ', 'ẹ', 'ẻ', 'ẽ', 'ế', 'ề', 'ể', 'ễ', 'ệ', 'ỉ', 'ị', 'ọ', 'ỏ', 'ố', 'ồ', 'ổ', 'ỗ', 'ộ', 'ớ', 'ờ', 'ở', 'ỡ', 'ợ', 'ụ', 'ủ', 'ứ', 'ừ', 'ử', 'ữ', 'ự', 'ỳ', 'ỵ', 'ỷ', 'ỹ', '\u200b', '\u200c', '\u200d', '\u200e', '₫', '◇', '❄', '❣', '❤', '。', '️', '\ufeff', '，', '', '🍁', '🍂', '💋', '😉', '😔', '😥', 

In [7]:
str2int = {char:i for i, char in enumerate(chars)}
int2str = {i:char for i, char in enumerate(chars)}
encode = lambda s: [str2int[c] for c in s]
decode = lambda lst: ''.join([int2str[i] for i in lst])
print(encode('nguyễn gia bình'))
print(decode(encode('nguyễn gia bình')))

[29, 22, 36, 40, 145, 29, 2, 22, 24, 16, 2, 17, 68, 29, 23]
nguyễn gia bình


In [8]:
import torch
data = torch.tensor(encode(text), dtype=torch.long)
data.shape, data.dtype, data[:100]

(torch.Size([83454368]),
 torch.int64,
 tensor([ 35,  23, 103,   2,  27, 161,  18,   2,  17,  58,  35,  13,   2,   1,
           2,  16,  24,   2, 103,  24,   2,  39,  16,   2,  17, 142,  29,   2,
          32,  36,  66,   2,  23, 105, 103,  29,  22,   1,  29,  23, 156,   2,
          37, 143,   2,  32,  36,  66,   2,  28, 139,   2,  29, 134,  29,  22,
           2,  34, 105, 103,  29,  22,   2,  89,  59,  40,   2,  29,  64,   1,
          29,  23, 156,   2,  34,  16,  30,   2,  29,  23, 166,  29,  22,   2,
          17,  36, 153,  24,   2,  35,  33, 105,  16,   2,  23,  64,   1,  37,
          76,  29]))

In [9]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8
x_train = train_data[:block_size]
y_train = train_data[1:block_size+1]
for i in range(block_size):
    print(f'context: {x_train[:i+1]} => target: {y_train[i]}')


context: tensor([35]) => target: 23
context: tensor([35, 23]) => target: 103
context: tensor([ 35,  23, 103]) => target: 2
context: tensor([ 35,  23, 103,   2]) => target: 27
context: tensor([ 35,  23, 103,   2,  27]) => target: 161
context: tensor([ 35,  23, 103,   2,  27, 161]) => target: 18
context: tensor([ 35,  23, 103,   2,  27, 161,  18]) => target: 2
context: tensor([ 35,  23, 103,   2,  27, 161,  18,   2]) => target: 17


In [35]:
torch.manual_seed(42)
batch_size = 32
block_size = 8
device = 'cuda' if torch.cuda.is_available() else 'cpu'
def get_batch(split):
    data = train_data if split=='train' else val_data
    start_idx = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in start_idx])
    y = torch.stack([data[i+block_size:i+block_size+1] for i in start_idx])
    x = x.to(device)
    y = y.to(device)
    return x, y

# xb, yb = get_batch('train')
# print('inputs:')
# print(xb.shape)
# print(xb)
# print('targets:')
# print(yb.shape)
# print(yb)

In [36]:
batch_size = 4
block_size = 32
ix = torch.randint(len(data) - block_size, (batch_size,))
ix

tensor([23005158, 82952627, 77478748, 36757390])

In [37]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(42)
B, T, C = 32, 8, 32 # batch, time, channel
x = torch.rand(B, T, C)
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)
W = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) -> (B, T, T)
tril = torch.tril(torch.ones(T, T))
W = W.masked_fill(tril==0, float('-inf'))
W = F.softmax(W, dim=-1)
v = value(x) # (B, T, 16)
out = W @ v # (B, T, T) @ (B, T, 16) > (B, T, 16)
W[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.4513, 0.5487, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2947, 0.2783, 0.4270, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2191, 0.2147, 0.3137, 0.2525, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1967, 0.1663, 0.2031, 0.2164, 0.2174, 0.0000, 0.0000, 0.0000],
        [0.1449, 0.1583, 0.1539, 0.1774, 0.1584, 0.2071, 0.0000, 0.0000],
        [0.1366, 0.1427, 0.1384, 0.1606, 0.1536, 0.1445, 0.1236, 0.0000],
        [0.1170, 0.1169, 0.0999, 0.1216, 0.1214, 0.1216, 0.1333, 0.1683]],
       grad_fn=<SelectBackward0>)

In [93]:
class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)
    
    def forward(self, x):
        B, T, C  = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2, -1)/(C**0.5) #  (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        output = wei @ v # (B, T, T) @ (B, T ,C) > (B, T, C)
        return output

class MultiHeadAttention(nn.Module):
    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)
        
    def forward(self, x):
        x = torch.cat([h(x) for h in self.heads], dim=-1)
        x = self.proj(x)
        x = self.dropout(x)
        return x

class FeedForward(nn.Module):
    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4*n_embd),
            nn.ReLU(),
            nn.Linear(4*n_embd, n_embd),
            nn.Dropout(dropout)
        )
    def forward(self, x):
        return self.net(x)
    

class DecoderBlock(nn.Module):
    def __init__(self, n_embd, n_heads):
        super().__init__()
        head_size = n_embd//n_heads
        self.sa = MultiHeadAttention(n_heads, head_size)
        self.ff = FeedForward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)
    
    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ff(self.ln2(x))
        return x

class GPT(nn.Module):
    def __init__(self):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, n_embd)
        self.position_embedding = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[DecoderBlock(n_embd, n_heads=n_heads) for _ in range(n_layers)])
        self.ln = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
    
    def forward(self, idx, targets=None):
        B, T = idx.shape
        token_embd = self.token_embedding(idx)
        position_embd = self.position_embedding(torch.arange(T, device=device))
        x = token_embd + position_embd
        x = self.blocks(x)
        x = self.ln(x)
        logits = self.lm_head(x)
        
        if targets is not None:
            B, T, C = logits.shape
#             print(logits.shape, targets.shape)
            logits = logits.view(B*T, C)
            
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        else:
            loss = None
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -block_size:]
            logits, loss = self(idx_cond)
            logits = logits[:, -1, :]
            probs = F.softmax(logits, dim=-1)
            next_idx = torch.multinomial(probs, num_samples=1)
            idx = torch.cat((idx, next_idx), dim=1)
        return idx

In [94]:
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters).to(device)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

In [121]:
import os
from torch.optim import lr_scheduler

batch_size = 128 
block_size = 32 
max_iters = 20000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_heads = 4
n_layers = 4
dropout = 0.0
best_loss = 100000

model = GPT()
model = model.to(device)
if 'last_GPT.pt' in os.listdir('.'):
    model.load_state_dict(torch.load('last_GPT.pt', map_location=torch.device('cpu')))
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
scheduler = lr_scheduler.StepLR(optimizer, step_size=1000, gamma=0.3)
print('model has', sum(p.numel() for p in model.parameters())/1e6, 'M parameters')

model has 0.22637 M parameters


In [122]:
def get_batch(split):
    data = train_data if split=='train' else val_data
    start_idx = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in start_idx])
    y = torch.stack([data[i+1:i+block_size+1] for i in start_idx])
    x = x.to(device)
    y = y.to(device)
    return x, y
x, y =get_batch('train')
y.shape

torch.Size([128, 32])

In [123]:
from tqdm import tqdm
for i in range(max_iters):
    if i % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        if losses['val'] < best_loss:
            best_loss = losses['val']
            torch.save(model.state_dict(), 'best_GPT.pt')   
        print(f"step {i}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")
        
    xb, yb = get_batch('train')
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    torch.save(model.state_dict(), 'last_GPT.pt') 
    scheduler.step()

step 0: train loss 1.5937, val loss 1.6580
step 100: train loss 1.6105, val loss 1.6752
step 200: train loss 1.6057, val loss 1.6663
step 300: train loss 1.6077, val loss 1.6586
step 400: train loss 1.6055, val loss 1.6702
step 500: train loss 1.6038, val loss 1.6653
step 600: train loss 1.6011, val loss 1.6686
step 700: train loss 1.6036, val loss 1.6626
step 800: train loss 1.6021, val loss 1.6545
step 900: train loss 1.6001, val loss 1.6618
step 1000: train loss 1.5952, val loss 1.6576
step 1100: train loss 1.5826, val loss 1.6493
step 1200: train loss 1.5824, val loss 1.6490
step 1300: train loss 1.5795, val loss 1.6464
step 1400: train loss 1.5809, val loss 1.6423
step 1500: train loss 1.5782, val loss 1.6465
step 1600: train loss 1.5768, val loss 1.6495
step 1700: train loss 1.5770, val loss 1.6425
step 1800: train loss 1.5780, val loss 1.6437
step 1900: train loss 1.5772, val loss 1.6486
step 2000: train loss 1.5746, val loss 1.6447
step 2100: train loss 1.5718, val loss 1.6434


KeyboardInterrupt: 

In [144]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
text = 'nhớ em'
context = torch.asarray([encode(text)], dtype=torch.long, device=device)
print( context)
print((decode(con) for con in context))
print(decode(model.generate(context, max_new_tokens=200)[0].tolist()))

tensor([[ 29,  23, 156,   2,  20,  28]], device='cuda:0')
<generator object <genexpr> at 0x7d66b8c88c10>
nhớ em còn mây
giấu dẫu chắc cũng soi nhòa đất nước
trẻ quê chùa đêm đen sông quá hồng
ngó ngào quên dánh vũng nấc vời
ngày xưa về ầm chúm ngọt ngã
để lòng ngắm trong hồn nhung ươm con
ta trở đò trọn phố ph


In [102]:
torch.save(model.state_dict(), 'GPT.pt')

In [105]:
load_model = GPT().to(device)
load_model.load_state_dict(torch.load('GPT.pt', map_location=torch.device('cpu')))
laod_model.eval()
print(decode(load_model.generate(context, max_new_tokens=200)[0].tolist()))

 ải đã xa

bên sự anh mắt từng lờ biềc với xuân từng sa
nhìn thơ xanh với mình mây
tròn nơi lượn cái lòng chưa vời
cái gươ ngoài tháng mang nụ cười
sầu bình trời mỹ đêm quận thương
giữ lòng soi thẩn b
